// artist-excursion.thoughts.js
// Creative Thoughts reel — label + 2–3 sentence prompt ending with a question

export const THOUGHTS = [
  { label: 'Seed', description: 'What is the smallest version of today’s idea I can plant in under ten minutes so it grows while I sleep? If I only water one square inch of the garden, which square needs it most today?' },
  { label: 'Frontier', description: 'Where did my comfort end and my curiosity begin today? If I stepped one notch past that frontier—gently and safely—what experiment would I try?' },
  { label: 'Texture', description: 'If today’s mood had a texture in my hands—grainy, slick, cotton-soft—how would it feel? How could I translate that sensation into line, rhythm, or color right now?' },
  { label: 'Pulse', description: 'What rhythm did this place teach my body—largo, andante, presto? Where could that beat live inside the next draft?' },
  { label: 'North', description: 'Which value quietly guided my choices today—truth, kindness, courage, play? How will I honor that value with one specific action tomorrow?' },
  { label: 'Bridge', description: 'What is the simplest bridge between inspiration and a scrappy proof I can ship? Which tiny artifact—thumbnail, voice note, or test riff—could cross the gap today?' },
  { label: 'Shed', description: 'What expectation of perfection can I set down so the real song can breathe? If I dropped one “should,” what would I pick up instead?' },
  { label: 'Spark', description: 'When exactly did my attention light up—what sight, sound, or scent did it ride in on? How can I recreate those conditions on purpose?' },
  { label: 'Lens', description: 'If I looked at this moment as a scientist, a poet, and a comedian, which lens revealed the next step? Which lens do I choose for tomorrow’s session?' },
  { label: 'Weight', description: 'What felt heavy today and what felt light in my system? How can I redistribute that weight so the work lifts me?' },
  { label: 'Chord', description: 'Which two ideas are already harmonizing in me, and what third note would complete the chord? Where will I place that note so the song resolves?' },
  { label: 'Anchor', description: 'What simple cue—a scent, a pen, a phrase—drops me into flow in sixty seconds or less? Where will I place that anchor so it meets me at start time?' },
  { label: 'Orbit', description: 'What theme keeps circling back no matter what I make? If I chose to orbit it on purpose, what would the next lap look like?' },
  { label: 'Window', description: 'Where is the small opening I can slip a rough draft through today? What can I complete in one intentional fifteen‑minute window?' },
  { label: 'Signal', description: 'What signal told me “enough for now”—a yawn, a sigh, a dimming? How will I honor that signal tomorrow without guilt?' },
  { label: 'Map', description: 'If the next three steps were landmarks, what would I call them and where would I rest? Which landmark do I head toward first?' },
  { label: 'Tide', description: 'When does my energy rise and when does it ebb? What task belongs at high tide and what ritual belongs at low tide?' },
  { label: 'Thread', description: 'Which single thread, if tugged, loosens today’s knot? How will I protect ten minutes to pull only that thread?' },
  { label: 'Proof', description: 'What would convince skeptical‑me that progress is real today? What receipt will I file before closing?' },
  { label: 'Echo', description: 'What motif echoed across my day, and how might repeating it intentionally strengthen my work? Where will I place the rhyme?' },
  { label: 'Frame', description: 'If I change the frame—audience, scale, or constraint—what new meaning appears? Which frame serves both my nervous system and my story best?' },
  { label: 'Kindness', description: 'What is the kindest way to continue this project without losing momentum? What boundary or adjustment would protect both me and the work?' },
  { label: 'Compass', description: 'Do I need Risk, Rest, or Reveal in the next hour? What would choosing that cardinal direction look like in practice?' },
  { label: 'Pattern', description: 'Which habit helped and which one quietly harmed today? What tiny swap would give me the same payoff with less cost?' },
  { label: 'Breathe', description: 'If the next action was inhale/hold/exhale, what would each phase be? How can breath set the pace of my doing?' },
  { label: 'Permission', description: 'What am I allowed to do while I learn—start messy, ask for help, change my mind? Will I sign that permission slip now?' },
  { label: 'Focus', description: 'If I could bring only one tool or idea into tomorrow’s session, which earns the seat? What gets left outside the door?' },
  { label: 'Scale', description: 'What happens if I shrink the scope by ten percent so shipping becomes obvious? What would I cut that actually feels like relief?' },
  { label: 'Portal', description: 'What sixty‑second ritual ushers me from life to making—tea, three taps, one stretch? What will I call that portal so I remember to use it?' },
  { label: 'Mirror', description: 'What did today reflect about my true taste versus borrowed taste? Which reflection feels honest enough to keep?' },
  { label: 'Chord‑Cut', description: 'Which obligation isn’t mine to hold anymore? What clean cut can I make to create space for the real song to emerge?' },
  { label: 'Draft', description: 'What lovable “bad” first version can I finish before bed? How will I celebrate the draft instead of chasing perfection?' },
  { label: 'Spine', description: 'If I write the story spine in five beats, what’s missing? How will I design tomorrow’s session to supply the missing beat?' },
  { label: 'North Star', description: 'How can I translate today’s guiding value into one measurable behavior for the week? Will I track it visibly so momentum compounds?' },
  { label: 'Why', description: 'Why now, and why me, for this piece? Which answer actually energizes me enough to pin it to the top of the file?' },
  { label: 'Pair', description: 'Which two unrelated notes could pair into a novel concept? How might their duet sound in three different arrangements?' },
  { label: 'Contour', description: 'If I outline the silhouette of the idea, what inside can be simplified? Which interior flourish can I remove to reveal the true form?' },
  { label: 'Glide', description: 'Where can I use momentum instead of willpower? What easy win can I chain directly before the hard task so I glide into it?' },
  { label: 'Tend', description: 'Which needs watering: skill, audience, rest, or system? What is the smallest tending act I will do today?' },
  { label: 'Title', description: 'What working title makes me want to show up? How does that title change my next move?' },
  { label: 'North‑East', description: 'If North is value and East is experiment, what test proves my value in practice? What result would count as proof?' },
  { label: 'Shimmer', description: 'Which small detail shimmered for me, and how will I spotlight it? What happens if I elevate it to centerpiece in a micro‑study?' },
  { label: 'Gate', description: 'What single decision would unlock the next stage? What simple criterion will help me make that call today?' },
  { label: 'Quiet', description: 'What noise can I subtract so the core speaks—one platform, one tab, one obligation? What will I remove for this cycle?' },
  { label: 'Borrow', description: 'Whose practice can I borrow for one day and make my own? Which part will I keep after the test?' },
  { label: 'Grip', description: 'Where am I holding too tight—deadline, standard, scope? What loosening by one notch might actually improve the work?' },
  { label: 'Swap', description: 'If I trade places with my future audience for a minute, what do they need first? What entry ramp will I build today?' },
  { label: 'Scale‑Up', description: 'If this had to serve ten people tomorrow, what would I change? What’s the simplest piece I can harden today?' },
  { label: 'Contour‑Cut', description: 'If I trim the idea to postcard size, what remains truest? What silhouette will I keep and what will I lovingly set aside?' },
  { label: 'Aftercare', description: 'What gentle after‑step helps me want to return tomorrow—tidy tools, a short note, water, or a stretch? Which aftercare will I do before I close?' },
  { label: 'Roots', description: 'What root need is the work feeding—belonging, expression, safety, wonder? How can I feed that root outside the work too?' },
  { label: 'Branches', description: 'Where is the piece branching too fast and stealing sap from the trunk? Which branch will I prune lovingly today?' },
  { label: 'Sun', description: 'What warmed me open creatively today? How can I tilt toward more of that light tomorrow?' },
  { label: 'Shade', description: 'What small shade did I need to recover—quiet, slowness, screens off? Where can I plant that shade on purpose?' },
  { label: 'Ground', description: 'Where do my feet meet the ground in this project—what is stable? How will I stand there before I leap?' },
  { label: 'Flow', description: 'What tiny change turns strain into glide—tempo, posture, playlist, or place? Which change will I test for one day?' },
  { label: 'Shadow', description: 'What part of me felt ignored, jealous, or scared during the work? How can I give that part a job so it travels with me instead of against me?' },
  { label: 'Integration', description: 'What insight from therapy, dreamwork, or meditation wants a seat at the table? How will I integrate it into one concrete move?' },
  { label: 'Boundary', description: 'Where did I leak energy today—overhelping, overchecking, overperfecting? What kind line can I draw for myself or others?' },
  { label: 'Attunement', description: 'What signals did my body send—tight jaw, warm chest, flutter belly—and how did I respond? What would a more caring response look like next time?' },
  { label: 'Clearing', description: 'What micro‑clutter blocks my path to the page—tab, thought, or pile? What 90‑second clearing could make a runway?' },
  { label: 'Call', description: 'If my muse called today, what number did she dial—curiosity, play, grief, relief? How can I keep the line open tomorrow?' },
  { label: 'Answer', description: 'What question did the place ask me back? What one‑line answer do I want to carry forward?' },
  { label: 'Attitude', description: 'What stance served the work—beginner’s mind, trickster, monk, or host? How can I put that stance on like a jacket tomorrow?' },
  { label: 'Offering', description: 'What small gift can I offer the work or community today—credit, thanks, an open‑source note? How will I make it visible?' },
  { label: 'Receiving', description: 'Where can I let help in without debt—feedback, rest, money, or time? What am I truly willing to receive this week?' },
  { label: 'Cycle', description: 'Where am I in the creative cycle—seed, sprout, bloom, compost? What does this phase need and what can wait?' },
  { label: 'Devotion', description: 'If I treated this practice like a devotional, what would I repeat daily? What simple vow would feel loving rather than punishing?' },
  { label: 'Ceremony', description: 'What small ceremony marks beginnings or endings so my body trusts me? What will I light, write, or ring?' },
  { label: 'Repair', description: 'Where did I rupture trust with myself or another today? What repair action would restore the fabric gently?' },
  { label: 'Charge', description: 'Where does energy pool in my body when the idea feels alive? How can I route that charge into one action before it dissipates?' },
  { label: 'Drain', description: 'What task reliably drains me, and what buffer or buddy system helps? How can I shrink the drain by ten percent?' },
  { label: 'Signal Fire', description: 'What visible sign will tell Future‑Me the trail is safe—a checklist, a note, or a laid‑out tool? Where will I place that signal before I leave?' },
  { label: 'Threshold', description: 'What doorway am I afraid to cross—publishing, asking, or finishing? What symbol or gesture could help me step through?' },
  { label: 'Contact', description: 'What did I truly make contact with today—material, person, memory, or place? What contact do I want to deepen tomorrow?' },
  { label: 'Consent', description: 'Did I ask my body and schedule for consent before I piled on? What would a consensual plan look like this week?' },
  { label: 'Awe', description: 'What small awe did I experience, and how can I widen that crack? Where will I go hunting for awe next?' },
  { label: 'Play', description: 'Where did play sneak in and loosen the gears? What rule could I bend to invite more play safely?' },
  { label: 'Honesty', description: 'What truth would unclench this piece if I dared to say it? How can I say it in a form that feels kind?' },
  { label: 'Mystery', description: 'What question is sweeter than any answer right now? How can I design tomorrow so the mystery stays alive?' },
  { label: 'Release', description: 'What can I stop forcing that might bloom if left alone? What do I hand back to the river?' },
  { label: 'Reframe', description: 'If I swap “should” for “could,” what opens? What sentence reframe will I try for 24 hours?' },
  { label: 'Witness', description: 'What wants to be witnessed without fixing—grief, pride, or fatigue? How will I sit with it long enough to hear the next cue?' },
  { label: 'Practice', description: 'If the point is practice, not performance, what changes? What tiny drill would make performance inevitable later?' },
  { label: 'Kind Mirror', description: 'If a loving mentor narrated my day, what would they highlight? Can I borrow that voice for one paragraph?' },
  { label: 'Future Postcard', description: 'What do I want Future‑Me to receive in the mail from today? What single line will I write on it?' },
  { label: 'Constraint', description: 'Which constraint turned out to be a kindness—timebox, monochrome, or one tool? What new constraint might free me next?' },
  { label: 'Signature', description: 'What element felt most mine—a tempo, a curve, a phrasing? Where will I sign with it tomorrow?' },
  { label: 'Repair Kit', description: 'What belongs in my creative first‑aid kit—walk, water, stretch, or song? Which item will I use before I push on?' },
  { label: 'Shadow Gift', description: 'What gift hides inside the part I judge—stubbornness as perseverance, envy as compass? How can I use the gift without the sting?' },
  { label: 'Tend the Child', description: 'What would my inner child love to make for fifteen minutes—glitter mess, goofy rhyme, or a cardboard crown? Will I give them the room?' },
  { label: 'Elder Counsel', description: 'What would my wise elder self advise about this stuck spot? What single sentence will I follow?' },
  { label: 'Guardian', description: 'If this project had a guardian spirit, what boundary would it set for me? What promise will I make to that guardian?' },
  { label: 'Signal vs. Noise', description: 'What input felt like signal and what felt like static today? What knobs will I turn down tomorrow?' },
  { label: 'Hospice for Ideas', description: 'Which idea needs a gentle goodbye so others can live? How will I honor it as I let it go?' },
  { label: 'Return', description: 'What practice has worked before that I forgot—walks, morning pages, or two‑song sprints? What will I return to for one week?' },
  { label: 'Ritual Exit', description: 'What simple closing ritual helps me stop while it’s still fun? How will I stage tomorrow’s re‑entry before I shut the door?' },
  { label: 'Embodiment', description: 'If the piece was a posture, what shape is it—curled, reaching, or grounded? What movement could I do that matches it?' },
  { label: 'Attic & Basement', description: 'What bright attic ideas need labeling, and what basement feelings need light? Which floor will I visit first?' },
  { label: 'Beacon', description: 'What am I signaling across the water to strangers like me? What single image or sentence does that best?' },
  { label: 'Integration Nap', description: 'Would a short rest integrate this better than more effort? Can I schedule recovery as strategy?' },
  { label: 'Friction', description: 'Where does good friction sharpen me and where does it burn me out? What lubricant—process, boundary, or humor—will I apply?' },
  { label: 'Lineage', description: 'Whose creative lineage am I part of, and what thread can I carry forward? How will I acknowledge them in my next piece?' },
  { label: 'Sacred No', description: 'What do I lovingly decline so the work can thrive? How will I say that no in a way that honors everyone involved?' },
  { label: 'Sacred Yes', description: 'What tiny yes do I whisper that changes the whole day? What proof will I make of that yes?' },
  { label: 'Threshold Guardian', description: 'What fear guards the door, and what offering does it want—information, time, or company? What offering can I make today?' },
  { label: 'Energy Budget', description: 'If I had 100 energy points, where did they go? How will I budget tomorrow so I still have points for play?' },
  { label: 'Harvest', description: 'What can I harvest now—phrases, textures, or color swatches—without finishing the whole field? Where will I store today’s gleanings?' },
  { label: 'Weather', description: 'What is the weather inside me—mist, sunbreak, or thunder far off—and how does the project dress for it? What forecast do I want to write?' },
  { label: 'Gate of Enough', description: 'What would “enough” look like for this session—one page, one loop, or one ask? How will I know I’ve crossed the gate?' },
  { label: 'Reciprocity', description: 'What did I take from the place, and what did I give back—trash picked, credit given, or quiet kept? How will I practice reciprocity tomorrow?' },
  { label: 'Synchronicity', description: 'What coincidences tapped my shoulder today? If I followed the thread of one, where would it lead?' },
  { label: 'Gentle Discipline', description: 'What loving structure—timer, buddy text, or playlist—keeps me steady without harshness? Which one will I try next?' },
  { label: 'Threshold Song', description: 'If crossing into the work had a song, what would it sound like? Will I hum three bars before I begin?' },
  { label: 'Clarity Cue', description: 'What question instantly clarifies my next move—What’s the verb, the feeling, or the “who for”? Which cue will I write on a sticky?' },
  { label: 'Compassion Audit', description: 'Was I as kind to myself as I would be to a friend doing brave work? What one kinder thing will I say or do next time?' },
  { label: 'Reverence', description: 'What deserves reverence here—time, tools, the subject, or my body? How can I show reverence without rigidity?' },
  { label: 'Threshold Gift', description: 'What small token will I place at the doorway to thank the day—one sentence, one breath, or one bow? What will I give today?' },
  { label: 'Playground', description: 'Where can I make a sandbox version of this idea to try rules with no stakes? What sandbox rule sounds fun?' },
  { label: 'Pilgrimage', description: 'If this project is a pilgrimage, what is today’s waystation stamp? What stamp will I collect tomorrow?' }
];

export default THOUGHTS;
