// artist-excursion.locations.js
export const LOCATIONS = [
  'Local Bookstore',
  'Library',
  'Museum',
  'Artist-run Gallery',
  'Open studios night',
  'Sculpture Garden',
  'Outdoor Art Walk',
  'Underpass Mural',
  'Botanical Garden',
  'Plant Nursery',
  'Butterfly House',
  'Nature Trail',
  'Riverwalk',
  'Bird Sanctuary',
  'Boardwalk / Pier',
  'Pet Store',
  'Bridge walkway',
  'Campground Picnic Area',
  'Community Garden',
  'Farmer’s Market',
  'Flea market',
  'Thrift store',
  'Observatory',
  'Art Supply Store',
  'Camera shop',
  'Vintage Record store',
  'Rock Shop',
  'Tea house',
  'Café',
  'Bakery',
  'International Grocery',
  'Aquarium',
  'Pottery Studio',
  'Instrument Store',
  'End-of-line Transit',
  'Airport Viewing Area',
  'Civic plaza',
  'Courthouse Lawn',
  'City Overlook',
  'Hilltop',
  'Humane Society',
  'Restaurant Rooftop',
  'Hotel Lobby',
  'Art Installation',
  'Stadium',
  'Community Pool',
  'Park Chess Tables',
  'Indie Cinema',
  'Theater',
  'Shoe Store',
  'Skating Rink',
  'Bowling Alley',
  'Vintage Arcade',
  'Meditation Center Foyer',
  'Labyrinth',
  'Cemetery stroll',
  'Makerspace',
  'Repair café',
  'Skatepark',
  'Board Game Café',
  'Cat café / Dog cafe',
  'Manga café',
  'Food-truck Park',
  'Interactive Art Exhibit',
  'Co-working Atrium',
  'Golf Course',
  'Climbing Wall',
  'Vintage Toy Store',
  'Dog Park',
  'Waterfall Overlook',
  'Orchard',
  'Pond',
  'Lake',
  'Barbershop / Hair salon',
  'Dollar store',
  'Pawn shop',
  'Office Supply Store',
  'Bus Stop',
  'Overpass',
  'Karaoke Booth',
  'Bubble Tea Bar',
  'Ice Cream Shop',
  'Ramen Shop',
  'Juice Bar',
  'Tattoo Studio',
  'Dance Studio',
  'Escape Room',
  'Best Friends House',
  'Grandmas House'
];

export default LOCATIONS;
